# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d21c2d7660bfa7876cbf165bdfb9de4f734074f242a4261829fbb8c43e805e63f87384d29edabac453b970d29ba8786ed6f1a92976c38054e50fa22f78501887

test:
  secret_key_base: f715ea04908741593aa732ac1e730801a54590837d511c25627a60ef577f1f581e1bed63973361129bc34621d16f5ffcc4de4b80f6ca0d4514e2556cd9dfbb21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
